from fastapi import FastAPI
from pydantic import BaseModel
from typing import Optional

app = FastAPI(title="Sati Library AI Engine")

class BookQuery(BaseModel):
    title: str
    author: Optional[str] = None

@app.get("/")
def read_root():
    return {"message": "Welcome to Sati Library AI Engine", "version": "1.0.0"}

@app.post("/summarize")
async def summarize_book(query: BookQuery):
    # This is a placeholder for future AI logic (e.g. specialized LLM processing)
    # For now, the PHP backend calls Gemini directly for simplicity,
    # but we keep this structure for modularity.
    return {
        "title": query.title,
        "summary": f"This is a placeholder summary for {query.title} generated by the FastAPI AI engine."
    }

@app.get("/recommendations")
async def get_recommendations():
    return [
        {"id": 1, "title": "Brave New World", "author": "Aldous Huxley"},
        {"id": 2, "title": "The Hobbit", "author": "J.R.R. Tolkien"},
        {"id": 3, "title": "Fahrenheit 451", "author": "Ray Bradbury"}
    ]
